### ISSUE TITLE
statusCode can`t be greater than 599 

### ISSUE THREAD

**Issue by jhva** [juliansteenbakker/mobile_scanner#1107]
hi!

My company is currently distributing apps to the Google Store.

It has been confirmed that the deployed app uses the mobile version v.3.5.5.

However, Regarding the response from Google Console, it has been reported that issue occurs in SDK 33,34.
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 4005 >>> com.kr.exmaple <<<

backtrace:
  #00  pc 0x00000000009ef388  /vendor/lib64/egl/libGLES_mali.so
  #01  pc 0x00000000009f1bc0  /vendor/lib64/egl/libGLES_mali.so
  #02  pc 0x0000000000a044fc  /vendor/lib64/egl/libGLES_mali.so
  #03  pc 0x0000000000a037c0  /vendor/lib64/egl/libGLES_mali.so
  #04  pc 0x000000000002de94  /system/lib64/libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int)+748)
  #05  pc 0x000000000002a498  /system/lib64/libEGL.so (eglSwapBuffers+80)
  #06  pc 0x0000000000019b60  /data/app/ com.kr.exmaple-yXtIhotSgRrgQuTAkInUjA==/split_config.arm64_v8a.apk
```
To solve this problem, the library version was too old, so I looked to see if there had been any updates. After seeing that the life cycle issue had been resolved starting from 5.0.0, I ran it again and the problem was resolved. 

After recognizing that the problem was resolved, I redistributed it to the Google Store and monitored the status, and now I received a report that the same error is occurring in sdk29. Is this part related to the mobile scanner library? 

My local Flutter version is below:

```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B2073 darwin-arm64, locale ko-KR)
    • Flutter version 3.22.2 on channel stable at /Users/kimjeonghun/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3주 전), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kimjeonghun/Library/Android/sdk
    • Platform android-34-ext11, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.
```

This is the pubspec.yaml content of the project where the error occurs.
```
ersion: 1.5.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.0.1
  url_launcher: ^6.1.11
  local_auth: ^2.1.6
  local_auth_darwin: ^1.3.1
  provider: ^6.1.1
  uni_links: ^0.5.1
  image_picker: ^1.0.4
  qr_code_dart_scan: ^0.7.3
  flutter_secure_storage: ^9.0.0
  flutter_downloader: ^1.10.5
  path_provider: ^2.1.1
  gal: ^2.2.0
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.8
  share_plus: ^7.2.1
  mobile_scanner: ^5.1.1
  lifecycle: ^0.8.0
  device_info_plus: ^10.1.0
  # intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

```

How can I resolve the error issue that occurs in sdk 29...?
