### ISSUE TITLE
Can't load gallery on my iPhone. Displayed [Unknown process name] CG***

### ISSUE THREAD

**Issue by yuchan2215** [juliansteenbakker/mobile_scanner#164]
Hi. sorry but I am using DeepL.

I am creating an app that reads QR codes from gallery.
Source: https://github.com/yuchan2215/flutterCodeScan/tree/13267165d874ed4a11caf600e99df848911f31a2/lib

Android can load from the gallery, but iOS (iPhone12 , iOS15.5) cannot.

Since the application is in Japanese, I will explain.
When you open the application, press the top button to use the camera and the bottom button to use the gallery.

Doctor:
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.67.2)
```

pubspec.yml
```
name: codereader
description: Two-dimensional code Reader

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner: ^1.1.1
  sliding_up_panel: ^2.0.0
  permission_handler: ^9.2.0
  mono_kit: ^0.27.1
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3
  after_layout: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

Output:
```
miyayu@MiyayunoMacBook-Pro flutterCodeScan % flutter run
Multiple devices found:
みっちゃんぴっぴ (mobile)    • 00008101-001609392E61001E • ios • iOS 15.5 19F77
MiyayuのiPad (mobile) • 00008101-000A41643461001E • ios • iOS 15.5 19F77
[1]: みっちゃんぴっぴ (00008101-001609392E61001E)
[2]: MiyayuのiPad (00008101-000A41643461001E)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on みっちゃんぴっぴ in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 55P4WP3SZP
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,775ms
Xcode build done.                                           13.3s
(lldb) 2022-05-30 15:50:17.262208+0900 Runner[15319:832494] Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Installing and launching...                                        19.3s
Syncing files to device みっちゃんぴっぴ...                                 48ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on みっちゃんぴっぴ is available at: http://127.0.0.1:49992/A-55orY7Kvc=/
The Flutter DevTools debugger and profiler on みっちゃんぴっぴ is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:49992/A-55orY7Kvc=/
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
[PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x282ce6820> accessor:<<PAApplication 0x280128f50 identifierType:auditToken identifier:{pid:15319, version:44792}>> identifier:E623DAD2-B7A2-4D7E-8BD3-555EFB807E90 kind:intervalEnd timestampAdjustment:0 tccService:kTCCServicePhotos, error=Error Domain=PAErrorDomain Code=10 "Possibly incomplete access interval automatically ended by daemon"
image_picker: compressing is not supported for type .png. Returning the image with original quality
[Unknown process name] CGBitmapContextCreate: invalid data bytes/row: should be at least 2340 for 16 integer bits/component, 1 components, kCGImageAlphaNone.
[Unknown process name] CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[Unknown process name] CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[Unknown process name] CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
flutter: MobileScanner: Called start() while already started!

```
