### ISSUE TITLE
FlashLight still remains on navigator pop, Camera preview blank when reopen screen

### ISSUE THREAD

**Issue by myoganugraha** [juliansteenbakker/mobile_scanner#23]
Debug on android, when flash is set on torch mode and close the page with navigator pop, the flash still remain
even open the scanner screen again, the flash indicator was off, but the flash still on torch mode

and the camera preview has blank
`I[/flutter]() ( 7098): MobileScanner: Called start() while already started!`

```
mobile_scanner: 
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
      ref: master
```

Google Pixel 3, Android 12
Flutter 2.2.3, Dart 2.12
