### ISSUE TITLE
ListView jumps with mobile_scanner on simulator running on M1 with Xcode 14.1

### ISSUE THREAD

**Issue by m-ochyra** [juliansteenbakker/mobile_scanner#392]
Flutter 3.3.9 and 3.0.5
MacBook Pro with M1 Pro
Xcode 14.1 and simulator with iOS 16.1 / 15.4

Edit:
mobile_scanner 2.1.0 and 3.0.0-beta.2

I have this problem after installing mobile_scanner: https://github.com/flutter/flutter/issues/79641.
I created a new blank project to trying reproduce this issue and after adding mobile_scanner package to project, it occurs. Without mobile_scanner everything is OK.
Problem is only on iOS simulators.

This is example code to reproduce issue:

main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: ListView.builder(
          itemCount: 200,
          itemBuilder: (_, index) => Text(index.toString()),
        ),
      ),
    );
  }
}
```

pubspec.yaml:
```yaml
name: test_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

Preview:
https://user-images.githubusercontent.com/5583015/205251779-ccbd249a-3079-4f41-b052-e450d17a5068.mov
