### ISSUE TITLE
Conflict with google_mlkit_face_detection

### ISSUE THREAD

**Issue by msaadbashir** [juliansteenbakker/mobile_scanner#580]
I am getting following error when trying to run mobile_scanner.

```
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In Podfile:
    google_mlkit_face_detection (from `.symlinks/plugins/google_mlkit_face_detection/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/FaceDetection (~> 3.2.0) was resolved to 3.2.0, which depends on
        GoogleMLKit/MLKitCore (= 3.2.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0)
```

My pubspec.yaml has following dependencies:

```
  cupertino_icons: ^1.0.2
  firebase_auth: 4.3.0
  firebase_core: 2.8.0
  google_fonts: ^4.0.1
  form_field_validator: ^1.1.0
  lottie: ^2.2.0
  image_picker: ^0.8.6+1
  path_provider: ^2.0.12
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  provider: ^6.0.5
  http: ^0.13.5
  animate_do: ^3.0.2
  pin_code_fields: ^7.4.0
  google_mlkit_face_detection: ^0.5.0
  google_mlkit_text_recognition: 0.5.0
  camera: ^0.10.3+2
  image: ^4.0.12
  dropdown_search: ^5.0.3
  percent_indicator: ^4.2.2
  geocoding: ^2.0.5
  location: ^4.4.0
  google_maps_flutter: 
  flutter_polyline_points: ^1.0.0
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  basic_utils: 5.5.3
  time_range: ^1.0.3
  jwt_decoder: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_background_service: ^2.4.6
  flutter_background_service_ios: ^2.4.0
  flutter_background_service_android: ^3.0.3
  shared_preferences: ^2.0.20
  barcode_widget: ^2.0.3
  encrypt: ^5.0.1
  socket_io_client: ^2.0.1
  geolocator: ^9.0.2
  intl: ^0.17.0
  mobile_scanner: ^3.2.0
```
