### ISSUE TITLE
setZoomScale doesn't work on iPhone 12 Pro

### ISSUE THREAD

**Issue by schilken** [juliansteenbakker/mobile_scanner#661]
With this initialization of MobileScannerController:
```
@override
  void initState() {
    super.initState();
    _detectedSerial = '';
    _cameraController = MobileScannerController(
      formats: [
        BarcodeFormat.all,
      ],
      detectionSpeed: DetectionSpeed.noDuplicates,
      detectionTimeoutMs: 1000,
      returnImage: false,
      autoStart: false,
    );
    _cameraController.events?.onData((data) {
      debugPrint('_cameraController.events: $data');
    });
    _cameraController.start();
    _cameraController.setZoomScale(0.8);
  }
```

I get an exception:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(MobileScanner, Error while zooming., null, null)
```

and the image is very small, not easy to scan small QR-codes of about 3cm sides.

Isn't anyone else having this problem?

I'm using Dart3 and Flutter 3.10.3, iOS 16.5.

**Comment by gaplo917** [comment]
I have the same issue, this issue is caused by the version `3.2.0` that default using ultra-wide camera in my iPhone 12 pro.

I found there is a PR fixed and merged, however, the latest `3.2.0` build don't have it
- #592 

I think you need to point the library to the master branch or the latest commit in `pubspec.yaml` and the reinstall it

```
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
      ref: master
```

latest commit of master
```
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
      ref: 5aa2c11915467b19dfc5fd3a9e59641d2958ffeb
```
