### ISSUE TITLE
Unable to Scan, Facing issue with Scanning

### ISSUE THREAD

**Issue by flutterrz** [juliansteenbakker/mobile_scanner#717]
1. Unable to scan from 1 meter distance
2. Unable to scan from few angels (LRTB)

Can you please help me on that ? Its very urgent for me

**Comment by flutterrz** [comment]
@juliansteenbakker Please look in below Pull Request. 

`analysisBuilder.setTargetResolution(Size(1440, 1920))`

- I have uncommented this line and it is giving me expected result, working fine and able to scan properly

[https://github.com/juliansteenbakker/mobile_scanner/pull/612](https://github.com/juliansteenbakker/mobile_scanner/pull/612)

**Comment by navaronbracke** [comment]
@flutterrz Does this still happen with https://github.com/juliansteenbakker/mobile_scanner/pull/721 applied?

You can test with (since the fix was not yet released)

```
dependencies:
 mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
```
